var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc('',undefined);
subject.inc('','utestingndefined');
subject.inc(-2,'utestingndefined');
subject.inc(2,'utestingndefined');
subject.weird(5,'','','');
subject.weird(9,'','','');
subject.weird(9,-2,'','');
subject.weird(9,2,'','');
subject.weird(9,2,40,'');
subject.weird(9,2,44,'');
subject.weird(9,2,44,"strict");
subject.weird(9,2,44,'"testingstrict"');
mock({"path/fileExists":{},"path/fileExists1":{"newContent":{"file2":"text content"}},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','demopath');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists','demopath');
mock.restore();
mock({"path/fileExists":{},"path/fileExists1":{"newContent":{"file2":"text content"}}});
	subject.fileTest('path/fileExists','demopath');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','demopath');
mock.restore();
mock({"path/fileExists":{},"path/fileExists1":{"newContent":{"file2":"text content"}},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists1','demopath');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists1','demopath');
mock.restore();
mock({"path/fileExists":{},"path/fileExists1":{"newContent":{"file2":"text content"}}});
	subject.fileTest('path/fileExists1','demopath');
mock.restore();
mock({});
	subject.fileTest('path/fileExists1','demopath');
mock.restore();
mock({"path/fileExists":{},"path/fileExists1":{"newContent":{"file2":"text content"}},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists1','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists1','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"path/fileExists1":{"newContent":{"file2":"text content"}}});
	subject.fileTest('path/fileExists1','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists1','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"path/fileExists1":{"newContent":{"file2":"text content"}},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists1','pathContent/file2');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists1','pathContent/file2');
mock.restore();
mock({"path/fileExists":{},"path/fileExists1":{"newContent":{"file2":"text content"}}});
	subject.fileTest('path/fileExists1','pathContent/file2');
mock.restore();
mock({});
	subject.fileTest('path/fileExists1','pathContent/file2');
mock.restore();
mock({"path/fileExists":{},"path/fileExists1":{"newContent":{"file2":"text content"}},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists1','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('path/fileExists1','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"path/fileExists1":{"newContent":{"file2":"text content"}}});
	subject.fileTest('path/fileExists1','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists1','pathContent/file1');
mock.restore();
subject.normalize('312-874-3764');
subject.normalize('');
subject.format('638-636-1670','','');
subject.format('','','');
subject.blackListNumber('052-095-5273');
subject.blackListNumber('');
subject.blackListNumber('212-147-7489');
