var subject = require('./subject.js')
var mock = require('mock-fs');
subject.inc('',undefined);
subject.inc('','utestingndefined');
subject.inc(-2,'utestingndefined');
subject.inc(2,'utestingndefined');
subject.weird(5,'','','');
subject.weird(9,'','','');
subject.weird(9,-2,'','');
subject.weird(9,2,'','');
subject.weird(9,2,40,'');
subject.weird(9,2,44,'');
subject.weird(9,2,44,"strict");
subject.weird(9,2,44,'"testingstrict"');
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','path/fileExists');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','path/fileExists');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','path/fileExists');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize('');
subject.format('','','');
subject.blackListNumber('');